### ISSUE TITLE
Does not work with yarn install

### ISSUE THREAD

**Issue by bjorn-dagerman** [saguijs/sagui#405]
Sagui requires Standard, which requires eslint. When installing with yarn, the following modules are not found when building:

~~~js
    eslint-plugin-react
    eslint-config-standard
    eslint-config-standard-jsx
~~~

Installing with yarns gives:
~~~
└──node_modules
    └──standard
        └──node_modules
            └──eslint-plugin-react
            └──...
~~~

Installing with npm gives:
~~~
└──node_modules
    └──standard
    └──eslint-plugin-react
    └──...
~~~

My version of yarn is 1.10 and npm 5.3.0.

Module build failed: Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: /Users/bjorn.dagerman/saguitest/.eslintrc
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugins.load (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/plugins.js:133:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/plugins.js:173:21)
    at loadFromDisk (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:536:35)
    at load (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.loadSpecificConfig (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config.js:139:46)
    at new Config (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/config.js:101:14)
    at new CLIEngine (/Users/bjorn.dagerman/saguitest/node_modules/eslint/lib/cli-engine.js:412:23)
    at Object.module.exports (/Users/bjorn.dagerman/saguitest/node_modules/eslint-loader/index.js:176:27)
 @ multi ./index

**Comment by pirelenito** [comment]
This should be fixed in `v11.2.0`.
